### PR TITLE
Bootstrap inital tests

### PR DESCRIPTION
**Pull request by dtthuynh**
Hypershift addon tests using golang/ginkgo.
Currently supports
- hypershift-addon health checks on hypershift operator (operator & external-dns), addon manager
- create/destroy path for aws, to be integrated into full acm e2e tests via ci
  - includes validation on addons and MC for create
  - validation on hostedcluster conditions for create
  - waits for & checks to make sure HC/MC CRDs are removed after destroy is finished
- tests that target cli route is available, each platform/arch can be downloaded
- options to add parameters either by env variables or options.yaml config file for multiple creations

 Next to be added:
- ci integration with Jenkins
- dockerfile to run tests as container 
- scaling tests
- kubevirt create/destroy

### CODE REVIEW

**Review by rokej — COMMENTED** [review]
@dtthuynh It looks good to me. A couple of comments. 1) It is still using the old "hypershift" CLI binary. 2) In destroy flow, should we check if the managedCluster is removed as well?

**Comment by dtthuynh** [comment]
> @dtthuynh It looks good to me. A couple of comments. 1) It is still using the old "hypershift" CLI binary. 2) In destroy flow, should we check if the managedCluster is removed as well?

Thank you @rokej ! I updated it to the new binary name, and also added additional binary tests in `e2e-go/pkg/test/hcp_aws_cli_route_test.go`

I also added this function to run after we do destroy, to check if the MC/HC are gone:
```
func WaitForClusterDetached(hubClientDynamic dynamic.Interface, clusterName string) {
	gomega.Eventually(func() bool {
		hasManagedCluster, err := HasResource(hubClientDynamic, ManagedClustersGVR, "", clusterName)
		if err != nil {
			ginkgo.Fail(err.Error())
		}
		return hasManagedCluster
	}, eventuallyTimeout, eventuallyInterval).Should(gomega.BeFalse())
	fmt.Printf("Cluster %s: successfully detached!\n\n", clusterName)
}

func WaitForHostedClusterDestroyed(hubClientDynamic dynamic.Interface, clusterName string) {
	gomega.Eventually(func() bool {
		hasManagedCluster, err := HasResource(hubClientDynamic, HostedClustersGVR, "", clusterName)
		if err != nil {
			ginkgo.Fail(err.Error())
		}
		return hasManagedCluster
	}, eventuallyTimeout, eventuallyInterval).Should(gomega.BeFalse())
	fmt.Printf("Hosted Cluster %s: successfully destroyed!\n\n", clusterName)
}
```
Let me know what you think. Hope this helps!

**Review by rokej — APPROVED** [review]
Thank you @dtthuynh

**Pull request merged**
